server:
    port: 8081
spring:
    application:
        name: TireManagementSystem-Registration
    datasource:
        url: jdbc:mysql://localhost:3306/mysqljdbc?createDatabaseIfNotExist=true
        username: user
        password: Angular@123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp